nav:
    - Introduction: index.md
    - Memory-safety: Memory-safety.md
    - Memory-debugger: Memory-debugger.md
    - Double-free: Double-free
    - Segment-fault: Segment-fault
    - Out-of-bound: Out-of-bound
    - Dereference-null-pointer: Dereference-null-pointer
    - Dangling-and-wild-pointer: Dangling-and-wild-pointer
    - OOM: OOM
    - Buffer-overflow: Buffer-overflow
    - Memory-leak: Memory-leak